-- Add agent-related fields to interviews table
-- This migration adds support for multi-agent interview types

-- Add agent_type column (defaults to 'custom' for existing records)
ALTER TABLE interviews 
ADD COLUMN IF NOT EXISTS agent_type TEXT NOT NULL DEFAULT 'custom';

-- Add agent_config column for runtime configuration overrides
ALTER TABLE interviews 
ADD COLUMN IF NOT EXISTS agent_config JSONB DEFAULT '{}';

-- Add research_brief column to store structured brief
ALTER TABLE interviews 
ADD COLUMN IF NOT EXISTS research_brief JSONB;

-- Add hume_system_prompt column to store generated Hume prompt
ALTER TABLE interviews 
ADD COLUMN IF NOT EXISTS hume_system_prompt TEXT;

-- Add workflow_state column to track wizard progress
ALTER TABLE interviews 
ADD COLUMN IF NOT EXISTS workflow_state JSONB DEFAULT '{"currentStep": "project-brief", "completedSteps": [], "inputData": {}}';

-- Add comment for documentation
COMMENT ON COLUMN interviews.agent_type IS 'Type of agent used for this interview (custom, product_feedback, nps, etc.)';
COMMENT ON COLUMN interviews.agent_config IS 'Runtime configuration overrides for the agent';
COMMENT ON COLUMN interviews.research_brief IS 'Structured research brief generated by the agent';
COMMENT ON COLUMN interviews.hume_system_prompt IS 'Generated Hume AI system prompt based on research brief';
COMMENT ON COLUMN interviews.workflow_state IS 'Current state of the interview creation wizard';

-- Create index on agent_type for faster queries
CREATE INDEX IF NOT EXISTS idx_interviews_agent_type ON interviews(agent_type);

-- Create index on workflow_state for progress tracking
CREATE INDEX IF NOT EXISTS idx_interviews_workflow_state ON interviews USING GIN (workflow_state);

-- Update existing records to have proper workflow state
UPDATE interviews 
SET workflow_state = jsonb_build_object(
  'currentStep', 'project-brief',
  'completedSteps', '[]'::jsonb,
  'inputData', '{}'::jsonb
)
WHERE workflow_state IS NULL OR workflow_state = '{}'::jsonb;

-- Verify the changes
DO $$ 
BEGIN
  RAISE NOTICE 'Agent fields added to interviews table successfully';
  RAISE NOTICE 'Columns: agent_type, agent_config, research_brief, hume_system_prompt, workflow_state';
  RAISE NOTICE 'Indexes: idx_interviews_agent_type, idx_interviews_workflow_state';
END $$;
